version: "3.12"

services:
  streamlit:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - deepwiki
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - GITHUB_TOKEN=${GITHUB_TOKEN:-""}
